spring:
  mvc:
    static-path-pattern: /resources/**

  datasource:
    url: jdbc:postgresql://localhost:5432/polyclinic
    username: postgres
    password: qnocks
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
